package:
  name: pysmesh
  version: 9.9.0

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [win]
    - cmake
    - ninja
    - boost-cpp ==1.74

  host:
    - python
    - pybind11
    - pyocct ==7.6.2
    - smesh ==9.9.0
    - tbb-devel
  run:
    - python
    - pyocct ==7.6.2
    - smesh ==9.9.0

test:
  source_files:
    - test
  requires:
    - pyocct

about:
  home: https://github.com/trelau/pySMESH
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for SMESH
  description: Python bindings for the Salome Platform SMESH module.
