package:
  name: pysmesh
  version: 9.6.0

source:
  path: ../..

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}  # [win]
    - cmake
    - ninja

  host:
    - python
    - pybind11
    - occt ==7.5.2
    - smesh ==9.6.0
    - netgen ==6.2.2006
    - tbb-devel
    - boost-cpp ==1.77.0
    - omniorb

  run:
    - python
    - occt ==7.5.2
    - netgen ==6.2.2006
    - smesh ==9.6.0
    - boost-cpp ==1.77.0
    - omniorb

test:
  source_files:
    - test
  requires:
    - pyocct ==7.5.2

about:
  home: https://github.com/trelau/pySMESH
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for SMESH
  description: Python bindings for the Salome Platform SMESH module.
